/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthLoopWriterSavedRouteImport } from './routes/_auth/loop-writer/saved'
import { Route as AuthLoopWriterCreateRouteImport } from './routes/_auth/loop-writer/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoopWriterSavedRoute = AuthLoopWriterSavedRouteImport.update({
  id: '/loop-writer/saved',
  path: '/loop-writer/saved',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoopWriterCreateRoute = AuthLoopWriterCreateRouteImport.update({
  id: '/loop-writer/create',
  path: '/loop-writer/create',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/loop-writer/create': typeof AuthLoopWriterCreateRoute
  '/loop-writer/saved': typeof AuthLoopWriterSavedRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/loop-writer/create': typeof AuthLoopWriterCreateRoute
  '/loop-writer/saved': typeof AuthLoopWriterSavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/loop-writer/create': typeof AuthLoopWriterCreateRoute
  '/_auth/loop-writer/saved': typeof AuthLoopWriterSavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/loop-writer/create' | '/loop-writer/saved'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/loop-writer/create' | '/loop-writer/saved'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/loop-writer/create'
    | '/_auth/loop-writer/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loop-writer/saved': {
      id: '/_auth/loop-writer/saved'
      path: '/loop-writer/saved'
      fullPath: '/loop-writer/saved'
      preLoaderRoute: typeof AuthLoopWriterSavedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loop-writer/create': {
      id: '/_auth/loop-writer/create'
      path: '/loop-writer/create'
      fullPath: '/loop-writer/create'
      preLoaderRoute: typeof AuthLoopWriterCreateRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthLoopWriterCreateRoute: typeof AuthLoopWriterCreateRoute
  AuthLoopWriterSavedRoute: typeof AuthLoopWriterSavedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthLoopWriterCreateRoute: AuthLoopWriterCreateRoute,
  AuthLoopWriterSavedRoute: AuthLoopWriterSavedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
